INSERT INTO tb_category (name,created_At) VALUES('Books', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Eletronics', NOW());
INSERT INTO tb_category (name,created_At) VALUES('Tools', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Eletronic Tools', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Hardware', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Toys', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Suits', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Accessories', NOW());
INSERT INTO tb_category (name,created_At) VALUES('Books', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Eletronics', NOW());
INSERT INTO tb_category (name,created_At) VALUES('Tools', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Eletronic Tools', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Hardware', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Toys', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Suits', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Accessories', NOW());
INSERT INTO tb_category (name,created_At) VALUES('Books', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Eletronics', NOW());
INSERT INTO tb_category (name,created_At) VALUES('Tools', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Eletronic Tools', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Hardware', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Toys', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Suits', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Accessories', NOW());
INSERT INTO tb_category (name,created_At) VALUES('Books', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Eletronics', NOW());
INSERT INTO tb_category (name,created_At) VALUES('Tools', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Eletronic Tools', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Hardware', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Toys', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Suits', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Accessories', NOW());
INSERT INTO tb_category (name,created_At) VALUES('Books', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Eletronics', NOW());
INSERT INTO tb_category (name,created_At) VALUES('Tools', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Eletronic Tools', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Hardware', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Toys', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Suits', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Accessories', NOW());
INSERT INTO tb_category (name,created_At) VALUES('Books', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Eletronics', NOW());
INSERT INTO tb_category (name,created_At) VALUES('Tools', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Eletronic Tools', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Hardware', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Toys', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Suits', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Accessories', NOW());
INSERT INTO tb_category (name,created_At) VALUES('Books', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Eletronics', NOW());
INSERT INTO tb_category (name,created_At) VALUES('Tools', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Eletronic Tools', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Hardware', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Toys', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Suits', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Accessories', NOW());
INSERT INTO tb_category (name,created_At) VALUES('Books', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Eletronics', NOW());
INSERT INTO tb_category (name,created_At) VALUES('Tools', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Eletronic Tools', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Hardware', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Toys', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Suits', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Accessories', NOW());
INSERT INTO tb_category (name,created_At) VALUES('Books', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Eletronics', NOW());
INSERT INTO tb_category (name,created_At) VALUES('Tools', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Eletronic Tools', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Hardware', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Toys', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Suits', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Accessories', NOW());
INSERT INTO tb_category (name,created_At) VALUES('Books', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Eletronics', NOW());
INSERT INTO tb_category (name,created_At) VALUES('Tools', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Eletronic Tools', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Hardware', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Toys', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Suits', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Accessories', NOW());
INSERT INTO tb_category (name,created_At) VALUES('Books', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Eletronics', NOW());
INSERT INTO tb_category (name,created_At) VALUES('Tools', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Eletronic Tools', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Hardware', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Toys', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Suits', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Accessories', NOW());
INSERT INTO tb_category (name,created_At) VALUES('Books', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Eletronics', NOW());
INSERT INTO tb_category (name,created_At) VALUES('Tools', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Eletronic Tools', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Hardware', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Toys', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Suits', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Accessories', NOW());
INSERT INTO tb_category (name,created_At) VALUES('Books', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Eletronics', NOW());
INSERT INTO tb_category (name,created_At) VALUES('Tools', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Eletronic Tools', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Hardware', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Toys', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Suits', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Accessories', NOW());
INSERT INTO tb_category (name,created_At) VALUES('Books', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Eletronics', NOW());
INSERT INTO tb_category (name,created_At) VALUES('Tools', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Eletronic Tools', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Hardware', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Toys', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Suits', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Accessories', NOW());
INSERT INTO tb_category (name,created_At) VALUES('Books', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Eletronics', NOW());
INSERT INTO tb_category (name,created_At) VALUES('Tools', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Eletronic Tools', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Hardware', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Toys', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Suits', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Accessories', NOW());
INSERT INTO tb_category (name,created_At) VALUES('Books', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Eletronics', NOW());
INSERT INTO tb_category (name,created_At) VALUES('Tools', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Eletronic Tools', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Hardware', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Toys', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Suits', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Accessories', NOW());
INSERT INTO tb_category (name,created_At) VALUES('Books', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Eletronics', NOW());
INSERT INTO tb_category (name,created_At) VALUES('Tools', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Eletronic Tools', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Hardware', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Toys', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Suits', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Accessories', NOW());
INSERT INTO tb_category (name,created_At) VALUES('Books', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Eletronics', NOW());
INSERT INTO tb_category (name,created_At) VALUES('Tools', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Eletronic Tools', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Hardware', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Toys', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Suits', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Accessories', NOW());
INSERT INTO tb_category (name,created_At) VALUES('Books', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Eletronics', NOW());
INSERT INTO tb_category (name,created_At) VALUES('Tools', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Eletronic Tools', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Hardware', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Toys', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Suits', NOW());
INSERT INTO tb_category (name, created_At) VALUES('Accessories', NOW());

